<?php
namespace App\Http\Controllers\Api;use App\Http\Controllers\Controller;use App\Models\{Account,Debt,DebtItem,Payment,Organization,Currency,DebtType,CashboxTransaction,AuditLog};use App\Services\{SettlementService,CreditBalanceService};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class CrudController extends Controller{protected string $model;public function index(Request $r){return $this->model::query()->paginate($r->integer('per_page',25));}public function show($id){return $this->model::findOrFail($id);}public function store(Request $r){return $this->model::create($r->all());}public function update(Request $r,$id){$m=$this->model::findOrFail($id);$m->update($r->all());return $m;}public function destroy($id){$this->model::findOrFail($id)->delete();return response()->noContent();}}
class AccountController extends CrudController{protected string $model=Account::class;public function statement(Account $account){return ['account'=>$account,'debts'=>$account->debts()->latest()->get(),'payments'=>$account->payments()->latest()->get(),'credits'=>$account->creditBalances()->get()];}}
class OrganizationController extends CrudController{protected string $model=Organization::class;}
class CurrencyController extends CrudController{protected string $model=Currency::class;}
class DebtTypeController extends CrudController{protected string $model=DebtType::class;}
class DebtController extends CrudController{protected string $model=Debt::class;public function store(Request $r){$data=$r->validate(['account_id'=>'required|exists:accounts,id','debt_type_id'=>'required|exists:debt_types,id','currency_id'=>'required|exists:currencies,id','amount'=>'required_without:items|numeric|min:0.01','issue_date'=>'required|date','due_date'=>'nullable|date','notes'=>'nullable|string','items'=>'array']);return DB::transaction(function()use($r,$data){$amount=collect($data['items']??[])->sum(fn($i)=>$i['quantity']*$i['unit_price']) ?: $data['amount'];$debt=Debt::create($data+['debt_no'=>'D-'.now()->format('YmdHis').random_int(100,999),'amount'=>$amount,'remaining_amount'=>$amount,'status'=>'open','created_by'=>$r->user()->id]);foreach($data['items']??[] as $item)$debt->items()->create($item+['organization_id'=>$debt->organization_id,'total'=>$item['quantity']*$item['unit_price']]);app(CreditBalanceService::class)->consume($debt);return $debt->load('items');});}}
class PaymentController extends CrudController{protected string $model=Payment::class;public function store(Request $r){$data=$r->validate(['account_id'=>'required|exists:accounts,id','currency_id'=>'required|exists:currencies,id','amount'=>'required|numeric|min:0.01','payment_date'=>'required|date','notes'=>'nullable|string']);$payment=Payment::create($data+['payment_no'=>'P-'.now()->format('YmdHis').random_int(100,999),'created_by'=>$r->user()->id]);app(SettlementService::class)->settle($payment);return $payment->load('allocations');}public function reverse(Payment $payment){$payment->update(['status'=>'reversed']);return $payment;}}
class DashboardController extends Controller{public function __invoke(){return ['total_outstanding'=>Debt::sum('remaining_amount'),'total_collected'=>Payment::where('status','posted')->sum('amount'),'total_accounts'=>Account::count(),'overdue_count'=>Debt::whereDate('due_date','<',today())->where('remaining_amount','>',0)->count(),'due_today'=>Debt::whereDate('due_date',today())->count(),'cashbox_balance'=>CashboxTransaction::sum('amount')];}}
class ReportController extends Controller{public function debts(Request $r){return Debt::query()->when($r->currency_id,fn($q)=>$q->where('currency_id',$r->currency_id))->get();}public function payments(Request $r){return Payment::query()->when($r->currency_id,fn($q)=>$q->where('currency_id',$r->currency_id))->get();}public function overdue(){return Debt::whereDate('due_date','<',today())->where('remaining_amount','>',0)->get();}public function export(Request $r){return response()->json(['message'=>'PDF/Excel export configured via DomPDF and Laravel Excel; bind concrete export classes per report.']);}}
