<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('organizations',function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->unique();$t->string('phone')->nullable();$t->string('email')->nullable();$t->text('address')->nullable();$t->string('logo')->nullable();$t->boolean('is_active')->default(true);$t->json('settings')->nullable();$t->timestamps();$t->softDeletes();});
Schema::table('users',function(Blueprint $t){$t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete()->index();$t->string('status')->default('active')->index();});
Schema::create('currencies',function(Blueprint $t){$t->id();$t->string('code',3)->unique();$t->string('name');$t->string('symbol',8);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('debt_types',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->nullable()->constrained()->cascadeOnDelete()->index();$t->string('name');$t->timestamps();$t->unique(['organization_id','name']);});
Schema::create('accounts',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete()->index();$t->string('account_no')->index();$t->string('name');$t->string('phone')->nullable();$t->string('email')->nullable();$t->text('address')->nullable();$t->text('notes')->nullable();$t->string('status')->default('active')->index();$t->timestamps();$t->softDeletes();$t->unique(['organization_id','account_no']);});
Schema::create('debts',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete()->index();$t->string('debt_no')->index();$t->foreignId('account_id')->constrained()->cascadeOnDelete()->index();$t->foreignId('debt_type_id')->constrained()->restrictOnDelete()->index();$t->foreignId('currency_id')->constrained()->restrictOnDelete()->index();$t->decimal('amount',18,2);$t->decimal('remaining_amount',18,2);$t->date('issue_date');$t->date('due_date')->nullable()->index();$t->text('notes')->nullable();$t->string('status')->default('open')->index();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->softDeletes();$t->unique(['organization_id','debt_no']);});
Schema::create('debt_items',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete()->index();$t->foreignId('debt_id')->constrained()->cascadeOnDelete()->index();$t->string('description');$t->decimal('quantity',18,3);$t->decimal('unit_price',18,2);$t->decimal('total',18,2);$t->timestamps();});
Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete()->index();$t->string('payment_no')->index();$t->foreignId('account_id')->constrained()->cascadeOnDelete()->index();$t->foreignId('currency_id')->constrained()->restrictOnDelete()->index();$t->decimal('amount',18,2);$t->date('payment_date')->index();$t->text('notes')->nullable();$t->string('status')->default('posted')->index();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();$t->softDeletes();$t->unique(['organization_id','payment_no']);});
Schema::create('payment_allocations',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete()->index();$t->foreignId('payment_id')->constrained()->cascadeOnDelete()->index();$t->foreignId('debt_id')->constrained()->cascadeOnDelete()->index();$t->decimal('allocated_amount',18,2);$t->timestamps();});
Schema::create('credit_balances',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete()->index();$t->foreignId('account_id')->constrained()->cascadeOnDelete()->index();$t->foreignId('currency_id')->constrained()->restrictOnDelete()->index();$t->decimal('amount',18,2)->default(0);$t->timestamps();$t->unique(['organization_id','account_id','currency_id']);});
Schema::create('cashbox_transactions',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete()->index();$t->string('transaction_type')->index();$t->decimal('amount',18,2);$t->foreignId('currency_id')->constrained()->restrictOnDelete()->index();$t->string('reference_type')->nullable();$t->unsignedBigInteger('reference_id')->nullable()->index();$t->text('notes')->nullable();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('dashboard_notifications',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->constrained()->cascadeOnDelete()->index();$t->string('title');$t->text('message');$t->string('type')->index();$t->boolean('is_read')->default(false)->index();$t->timestamps();});
Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete()->index();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete()->index();$t->string('action')->index();$t->string('entity_type');$t->unsignedBigInteger('entity_id')->nullable()->index();$t->json('old_values')->nullable();$t->json('new_values')->nullable();$t->timestamps();});
}public function down():void{foreach(['audit_logs','dashboard_notifications','cashbox_transactions','credit_balances','payment_allocations','payments','debt_items','debts','accounts','debt_types','currencies','organizations'] as $table)Schema::dropIfExists($table);}};
